services:
  - type: web
    name: django-app
    env: python
    buildCommand: ""
    startCommand: gunicorn configs.wsgi
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: configs.settings
