# Generated by Django 5.2.1 on 2025-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizationdata',
            name='all_phrases_analysis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='visualizationdata',
            name='analyzed_endpoint',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visualizationdata',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visualizationdata',
            name='global_frequency_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='visualizationdata',
            name='global_percentage_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='visualizationdata',
            name='input_transformed_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='visualizationdata',
            name='per_source_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='visualizationdata',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
