# Generated by Django 5.2.1 on 2025-06-02 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningdata',
            name='createdAt',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cleaningdata',
            name='source',
            field=models.URLField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cleaningdata',
            name='updatedAt',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
