# Generated by Django 5.2.1 on 2025-05-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningdata',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cleaningdata',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
