# Generated by Django 5.2.1 on 2025-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestiondata',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
